### ISSUE TITLE
Unable to install Arch

### ISSUE THREAD

**Issue by guihkx** [YadominJinta/atilo#104]
Hello,

I'm getting this error upon trying to install Arch on my aarch64 phone:

```
$ atilo pull arch
Pulling image
100%|█████████████████████████████████████████████████████████████████████| 576M/576M [02:47<00:00, 3.43MiB/s]
Checking file integrity
100%|██████████████████████████████████████████████████████████████████████| 576M/576M [00:04<00:00, 117MiB/s]
Checksum successfully
Extracting image
Configuring image
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/atilo", line 333, in <module>
    pull_image(sys.argv[2])
  File "/data/data/com.termux/files/usr/bin/atilo", line 135, in pull_image
    config_image(distro,infos)
  File "/data/data/com.termux/files/usr/bin/atilo", line 152, in config_image
    with open(resolv_conf,'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/data/com.termux/files/home/.atilo/arch/etc/resolv.conf'
```

Screenshot:

![image](https://user-images.githubusercontent.com/626206/98897103-66dfe200-2489-11eb-98ac-ce12acee60d6.png)

Tried Debian right after that and it worked, though.

**Comment by guihkx** [comment]
My `~/.atilo/arch/etc/` looks like this:

![image](https://user-images.githubusercontent.com/626206/98897383-0bfaba80-248a-11eb-9d19-aff05d20c4d2.png)

`~/.atilo/arch/etc/resolv.conf` is a broken symlink to `/run/systemd/resolve/resolv.conf`:

![image](https://user-images.githubusercontent.com/626206/98897541-685dda00-248a-11eb-971f-70636d2fcd1d.png)

**Comment by greenhandzdl** [comment]
```
~  atilo pull arch
Pulling image
100%|█████████████████████████████████████| 576M/576M [03:37<00:00, 2.64MiB/s]
Checking file integrity
100%|█████████████████████████████████████| 576M/576M [00:08<00:00, 66.0MiB/s]
Checksum successfully
Extracting image
Configuring image
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/atilo", line 333, in <module>
    pull_image(sys.argv[2])
  File "/data/data/com.termux/files/usr/bin/atilo", line 135, in pull_image
    config_image(distro,infos)
  File "/data/data/com.termux/files/usr/bin/atilo", line 152, in config_image
    with open(resolv_conf,'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/data/com.termux/files/home/.atilo/arch/etc/resolv.conf'
 ✘  ~  atilo run arch
You dont have archimage
Pull it before running it
```

**Comment by guihkx** [comment]
Yeah, this can be verified by downloading the aarch64 version of Arch:

http://os.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz

If you extract only the `resolv.conf` inside `/etc/`, you'll notice that it indeed points to `/run/systemd/resolve/resolv.conf`.

**Comment by YadominJinta** [comment]
I will drop arch support because I don't want to do more specific operation for the disgusting distro.
